

spring:
  thymeleaf:
    mode: LEGACYHTML5
    encoding: UTF-8
    content-type: text/html
    # 开发禁用缓存
    cache: false
    suffix: .html
  datasource:
    url: jdbc:mysql://localhost:3306/mydb?characterEncoding=UTF-8&useSSL=true
    username: root
    password:
    # 可省略驱动配置, sprin-boot 会由url检测出驱动类型
    # driver-class-name: com.mysql.jdbc.Driver
    hikari:
      connection-timeout: 60000
  redis:

    # Redis数据库索引（默认为0）
    database: 0
    host: localhost
    port: 6379
    password:
    pool:
      # 连接池最大连接数（使用负值表示没有限制）
      max-active: 20
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1
      # 连接池中的最大空闲连接
      max-idle: 8
      # 连接池中的最小空闲连接
      min-idle: 0
      # 连接超时时间（毫秒）
    timeout: 1000
mybatis:
  mapperLocations: classpath:com/boot/mapper/*.xml
  typeAliasesPackage: com.boot.domain
# spring-boot默认打印输出info级别以上的，可在此处修改输出级别
logging:
  level:
    root: info

server:
  #端口号
  port: 8888
